#!/usr/bin/env python3

from contextlib import nullcontext
from dialog import Dialog
import os
import json

jsonstr=os.popen('aws codecommit list-repositories --output json').read()


region = os.getenv('AWS_REGION') 


data = json.loads(jsonstr)

print(data["repositories"][0])

choicedata=list()

d = Dialog(dialog="dialog")

for repositories in data["repositories"]: 
        choicedata.append([repositories["repositoryName"], repositories["repositoryId"]])    
        
code, tag = d.menu("CodeCommit-Downloader",
                   choices=choicedata)

if code == d.OK:  
        os.system('clear')
        os.system(f"git clone ssh://git-codecommit.{region}.amazonaws.com/v1/repos/{tag}")
else:
        os.system('clear')
        print('CodeCommit-Downloader closed')
